steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/$PROJECT_ID/<service-endpoint>"
  - "--file=./Dockerfile.prod"
  - .

images:
- "gcr.io/$PROJECT_ID/<service-endpoint>"